# Default values for hyperledger-fabric.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fabric:
  binaries: "1.2.0"

image:
  cryptogen:
    repository: gcr.io/dazwilkin-180827-fabric/cryptogen
    tag: "1.2.0"
    pullPolicy: IfNotPresent
  configtxgen:
    repository: gcr.io/dazwilkin-180827-fabric/configtxgen
    tag: "1.2.0"
    pullPolicy: IfNotPresent   
  ca:
    # Is not built as part of Hyperledger Fabric build
    repository: hyperledger/fabric-ca
    tag: "1.2.0"
    pullPolicy: IfNotPresent
  cli:
    repository: hyperledger/fabric-tools
    tag: "1.2.0"
    pullPolicy: IfNotPresent
  orderer:
    repository: hyperledger/fabric-orderer
    tag: "1.2.0"
    pullPolicy: IfNotPresent
  peer:
    repository: hyperledger/fabric-peer
    tag: "1.2.0"
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Can't be hyphenated
cryptoconfig:
  OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
    - Hostname: orderer
  PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 5
    Users:
      Count: 5
  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true
    Template:
      Count: 5
    Users:
      Count: 5

# Values doesn't support YAML &anchors and *references
configtx:
  Organizations:
  - Name: Org1MSP
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
    AnchorPeers:
    - Host: peer0.org1.example.com
      Port: 7051
  - Name: Org2MSP
    ID: Org2MSP
    MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
    AnchorPeers:
    - Host: peer0.org2.example.com
      Port: 7051
