---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperledger-fabric.fullname" . }}-ca
  labels:
    app.kubernetes.io/name: {{ include "hyperledger-fabric.chart" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app: {{ include "hyperledger-fabric.name" . }}
    chart: {{ include "hyperledger-fabric.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: ca
spec:
  type: NodePort
  selector:
    app: {{ include "hyperledger-fabric.name" . }}
    chart: {{ include "hyperledger-fabric.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: ca
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054
    name: grpc
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyperledger-fabric.fullname" . }}-ca
  labels:
    app.kubernetes.io/name: {{ include "hyperledger-fabric.chart" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app: {{ include "hyperledger-fabric.name" . }}
    chart: {{ include "hyperledger-fabric.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: ca
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hyperledger-fabric.name" . }}
      chart: {{ include "hyperledger-fabric.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      component: ca
  template:
    metadata:
      labels:
        app: {{ include "hyperledger-fabric.name" . }}
        chart: {{ include "hyperledger-fabric.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: ca
    spec:
      volumes:
      - name: {{ include "hyperledger-fabric.fullname" . }}-shared-pvc
        persistentVolumeClaim:
          claimName: {{ include "hyperledger-fabric.fullname" . }}-shared-pvc
      initContainers:
      containers:
      - name: {{/*{{ .Chart.Name }}-*/}}ca
        image: "{{ .Values.image.ca.repository }}:{{ .Values.image.ca.tag }}"
        imagePullPolicy: {{ .Values.image.ca.pullPolicy }}
        command:
        - sh
        - -c
        - |
          fabric-ca-server start \
          --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem \
          --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY \
          -b admin:adminpw \
          -d
        ports:
          - name: grpc
            containerPort: 7054
            protocol: TCP
        volumeMounts:
        - mountPath: /shared
          name: {{ include "hyperledger-fabric.fullname" . }}-shared-pvc
...