---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "hyperledger-fabric.fullname" . }}-shared-pv
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Release.Name }}-nfs.{{ .Release.Namespace }}.svc.cluster.local
    path: "/"
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "hyperledger-fabric.fullname" . }}-shared-pvc
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ include "hyperledger-fabric.fullname" . }}-shared-pv
...

